/**
 * 数据调研页 —— 数据源元数据 + 连通性检测配置。
 * 数据与 docs/免费行情数据源调研报告.md 保持一致，按市场分类、按综合评分排序（高 → 低）。
 */

export type MarketId = 'astock' | 'us' | 'crypto' | 'futures' | 'fund';

export interface MarketInfo {
  id: MarketId;
  label: string;
  icon: string;
  desc: string;
}

export const MARKETS: MarketInfo[] = [
  { id: 'astock', label: 'A股', icon: '🇨🇳', desc: '沪深股票 / 指数' },
  { id: 'us', label: '美股', icon: '🇺🇸', desc: '美股 / 指数 / ETF / ADR' },
  { id: 'crypto', label: '加密货币', icon: '🪙', desc: '现货 K 线 + 实时推送' },
  { id: 'futures', label: '期货', icon: '📦', desc: '国内主力连续 / 海外商品' },
  { id: 'fund', label: '基金', icon: '🏦', desc: '场内 ETF K线 / 场外净值' },
];

/** 接入方式（一个源可同时具备多种） */
export type AccessKind = 'direct' | 'vpn' | 'proxy' | 'jsonp' | 'key' | 'server';

export const ACCESS_META: Record<AccessKind, { label: string; cls: string; title: string }> = {
  direct: { label: '直连', cls: 'ab-direct', title: '浏览器可直接请求（CORS 开放）' },
  vpn: { label: '🌐 需外网', cls: 'ab-vpn', title: '大陆网络通常不可达，需外网环境（科学上网）' },
  proxy: { label: '🔁 需代理', cls: 'ab-proxy', title: '无 CORS 头，需 Vite proxy / 后端 BFF 转发' },
  jsonp: { label: 'JSONP', cls: 'ab-jsonp', title: '用 <script> 标签注入绕过 CORS' },
  key: { label: '🔑 需Key', cls: 'ab-key', title: '需注册免费 API key' },
  server: { label: '服务端', cls: 'ab-server', title: '仅服务端库 / 后端环境可用，浏览器无法直连' },
};

export interface DataSourceInfo {
  id: string;
  name: string;
  market: MarketId;
  /** 定位：主源 / 备选 / 参考 / 排除 */
  role: '主源' | '备选' | '参考' | '排除';
  /** 综合评分 0~100（数据丰富度 + 稳定性 + 免费易用性），决定展示顺序 */
  score: number;
  /** 能力标签 */
  tags: string[];
  access: AccessKind[];
  /** 接入特别条件说明（外网 / 代理 / Key / 限频等） */
  accessNote: string;
  history: string;
  realtime: string;
  limits: string;
  /** 一句话结论 */
  reason: string;
  /** 连通性检测探针 URL（轻量 GET）。无该字段 = 服务端库/已排除，浏览器无法检测 */
  checkUrl?: string;
  checkNote?: string;
}

/** 各市场速览（首选 / 备选 / 接入方式） */
export const MARKET_SUMMARY: Record<MarketId, { primary: string; backup: string; note: string }> = {
  astock: { primary: '东方财富 push2his', backup: '腾讯 web.ifzq', note: '直连 · 限频 ≥2s' },
  us: { primary: 'Twelve Data', backup: 'Yahoo（需外网+代理）', note: '免费Key · 延时数据' },
  crypto: { primary: 'Binance（已接入）', backup: 'OKX → Bybit', note: '直连 · 无Key' },
  futures: { primary: '新浪 RB0 / Yahoo CL=F', backup: 'SHFE · CFFEX 官方 EOD', note: '需代理' },
  fund: { primary: '天天基金（场外净值）', backup: '东财 push2his（场内ETF）', note: '代理 / 直连(不稳)' },
};

export const SOURCES: DataSourceInfo[] = [
  // ================= A股 =================
  {
    id: 'astock-eastmoney',
    name: '东方财富 push2his/push2delay',
    market: 'astock',
    role: '主源',
    score: 92,
    tags: ['日线全历史', '复权', '分钟线', '实时延时', '字段最全', '无Key'],
    access: ['direct'],
    accessNote: '浏览器可直连；高频触发 SSL 断连/封 IP，务必限频 ≥2s + 失败退避',
    history: '日线上市以来全量；1m 仅近 5 交易日',
    realtime: '盘中实时（push2delay 延时约 15 分钟）',
    limits: '无官方限流声明，实测高频 HTTP 000 / IP 临时封禁',
    reason: '字段最全（额/振幅/涨跌幅/换手率）、复权齐全，A股主源首选',
    checkUrl:
      'https://push2his.eastmoney.com/api/qt/stock/kline/get?secid=1.600000&fields1=f1,f2,f3,f4,f5,f6&fields2=f51,f52,f53,f54,f55,f56,f57,f58&klt=101&fqt=1&beg=0&end=20500101&lmt=1',
  },
  {
    id: 'astock-tencent',
    name: '腾讯 web.ifzq / qt.gtimg.cn',
    market: 'astock',
    role: '备选',
    score: 82,
    tags: ['直连', '无Key', '日线全历史', '复权', 'GBK'],
    access: ['direct'],
    accessNote: '浏览器直连（ACAO:*）；返回 GBK 需 TextDecoder 转码',
    history: '日线上市以来全量，800 根/页滚动分页；分钟线单次 320 根',
    realtime: '盘中实时（qt.gtimg 30+ 字段）',
    limits: '宽松；偶发 301 切 web3 节点（SSL 不稳）',
    reason: '东财限流时的可靠降级通道；缺成交额/涨跌幅',
    checkUrl: 'https://qt.gtimg.cn/q=sh600000',
  },
  {
    id: 'astock-baostock',
    name: 'Baostock',
    market: 'astock',
    role: '参考',
    score: 70,
    tags: ['免费', '复权', 'Python库', '全历史'],
    access: ['server'],
    accessNote: '服务端 Python 库（TCP 行情服务器），浏览器无法直连',
    history: '日线上市以来全量 + 5/15/30/60 分钟',
    realtime: '无盘中',
    limits: '无 token；服务端长期无人维护（失效风险高）',
    reason: '后端批处理可用，数据与东财一致；维护停滞是隐患',
    checkNote: 'Python 库，需后端环境',
  },
  {
    id: 'astock-sina',
    name: '新浪财经（快照）',
    market: 'astock',
    role: '备选',
    score: 62,
    tags: ['秒级实时', 'JSONP', 'GBK'],
    access: ['jsonp', 'proxy'],
    accessNote: '无 CORS 头；2022 起实时必须带 Referer 否则 403；高频封 IP',
    history: '日K 单次约 1950 根（约 8 年）',
    realtime: '秒级快照',
    limits: '隐性限流强、频繁封 IP',
    reason: '只适合秒级快照补充，不适合主 K 线',
    checkUrl: 'https://hq.sinajs.cn/list=sh600000',
  },
  {
    id: 'astock-tushare',
    name: 'Tushare Pro',
    market: 'astock',
    role: '参考',
    score: 56,
    tags: ['需Key', '积分制', '稳定'],
    access: ['key', 'proxy'],
    accessNote: '需注册 token；120 分仅日线不复权；浏览器无法直连需后端',
    history: '日线上市以来全量',
    realtime: '日终更新',
    limits: '120 分档 50 次/分、8000 次/日；积分一年有效期',
    reason: '数据最稳但免费档逐年收紧，对纯前端项目偏重',
    checkNote: '需 token + 后端',
  },
  {
    id: 'astock-exchange',
    name: '沪深交易所官网',
    market: 'astock',
    role: '参考',
    score: 42,
    tags: ['官方', '文件下载', '日终'],
    access: ['proxy', 'server'],
    accessNote: '上交所风控不可达；深交所行情 API 半失效，只提供日终文件下载',
    history: '日线全市场（延时约 1 天）',
    realtime: '无',
    limits: '—',
    reason: '适合离线全市场归档，不适合演示主源',
    checkUrl: 'https://www.sse.com.cn/',
    checkNote: '上交所风控，多半不可达',
  },
  {
    id: 'astock-ths',
    name: '同花顺 iFinD / 问财',
    market: 'astock',
    role: '排除',
    score: 18,
    tags: ['反爬强'],
    access: ['server'],
    accessNote: 'iFinD 需院校授权；问财 401 + 复杂签名，反爬极强',
    history: '—',
    realtime: '—',
    limits: '—',
    reason: '不适用（免费入口几乎为零）',
    checkNote: '反爬强，不适用',
  },

  // ================= 美股 =================
  {
    id: 'us-twelve-data',
    name: 'Twelve Data',
    market: 'us',
    role: '主源',
    score: 88,
    tags: ['直连', '分钟线', '免费Key', '日线全历史'],
    access: ['direct', 'key'],
    accessNote: 'CORS * 可直连；免费档 8 credits/分、800/天；免费层限个人内部非展示用途',
    history: '日线 + 分钟线（1/5/15/30/60m），单次最大 5000 根',
    realtime: '日线/分钟延时',
    limits: '8 credits/min、800/day',
    reason: '唯一「直连 + 分钟线」的免费美股源',
    checkUrl: 'https://api.twelvedata.com/time_series?symbol=AAPL&interval=1day&outputsize=1&apikey=demo',
  },
  {
    id: 'us-yahoo',
    name: 'Yahoo Finance chart',
    market: 'us',
    role: '主源',
    score: 84,
    tags: ['数据最全', '指数/ETF/ADR', '免Key', 'adjclose'],
    access: ['vpn', 'proxy'],
    accessNote: '无 CORS 头需代理；大陆网络需外网环境；免 key 免 crumb',
    history: '日线 40+ 年（1984 起）；1m 仅近 7 天',
    realtime: '延时 15 分钟',
    limits: '无官方 SLA，长期高频 429',
    reason: '覆盖面最全，配 Vite proxy 是省事的海外全量源',
    checkUrl: 'https://query1.finance.yahoo.com/v8/finance/chart/AAPL?range=1d&interval=1d',
  },
  {
    id: 'us-sina',
    name: '新浪财经美股日K',
    market: 'us',
    role: '备选',
    score: 76,
    tags: ['免注册', '1984至今全历史', 'JSONP', 'GBK'],
    access: ['jsonp'],
    accessNote: '无 CORS 头，用 <script> 注入绕过；GBK 需转码',
    history: '1984-09 至今 10026 根全历史',
    realtime: '无',
    limits: '隐性限流、封 IP',
    reason: '免 key 的长历史兜底',
    checkUrl: 'https://hq.sinajs.cn/list=gb_aapl',
  },
  {
    id: 'us-finnhub',
    name: 'Finnhub',
    market: 'us',
    role: '备选',
    score: 68,
    tags: ['需Key', 'CORS', '分钟线'],
    access: ['direct', 'key'],
    accessNote: '免费注册 key；CORS 支持；免费档 WebSocket 有限',
    history: '约 5 年日线',
    realtime: '免费档有限',
    limits: '约 60 次/分（社区说法，未复核）',
    reason: '备选；配额需实测复核',
    checkUrl: 'https://api.finnhub.io/api/v1/quote?symbol=AAPL',
  },
  {
    id: 'us-alpha-vantage',
    name: 'Alpha Vantage',
    market: 'us',
    role: '参考',
    score: 52,
    tags: ['需Key', '25次/天', '20年日线'],
    access: ['direct', 'key'],
    accessNote: '免费档 25 次/天（2026 已大幅收紧）；key 暴露在 URL',
    history: '日线约 20 年；分钟线免费档不支持',
    realtime: '日终',
    limits: '25 次/天',
    reason: '配额过紧，仅演示级',
    checkUrl: 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=IBM&apikey=demo',
  },
  {
    id: 'us-tiingo',
    name: 'Tiingo',
    market: 'us',
    role: '参考',
    score: 50,
    tags: ['需Key', '30年历史'],
    access: ['key', 'proxy'],
    accessNote: '实测无 CORS 头（带 Origin 返回 403），需代理',
    history: '30+ 年日线',
    realtime: 'IEX 实时（免费档）',
    limits: '50 次/时、1000 次/天',
    reason: '配额紧 + 需代理',
    checkUrl: 'https://api.tiingo.com/tiingo/daily/AAPL/prices?startDate=2026-09-01&token=',
  },
  {
    id: 'us-stooq',
    name: 'Stooq',
    market: 'us',
    role: '排除',
    score: 28,
    tags: ['反爬验证墙'],
    access: ['server'],
    accessNote: '2026 起加 SHA-256 PoW JS 反爬验证墙，curl/浏览器均拿不到',
    history: '—',
    realtime: '—',
    limits: '—',
    reason: '反爬成本过高',
    checkNote: 'PoW 反爬墙，已不可直连',
  },
  {
    id: 'us-iex',
    name: 'IEX Cloud',
    market: 'us',
    role: '排除',
    score: 10,
    tags: ['已停服'],
    access: [],
    accessNote: '2024-08 已停止运营',
    history: '—',
    realtime: '—',
    limits: '—',
    reason: '已停服，勿接入',
    checkNote: '2024-08 已停服',
  },
  {
    id: 'us-nasdaq',
    name: 'Nasdaq Data Link / Quandl',
    market: 'us',
    role: '排除',
    score: 20,
    tags: ['付费'],
    access: [],
    accessNote: '美股 EOD 日线全为 Premium（付费）；WIKI 数据集已退役',
    history: '—',
    realtime: '—',
    limits: '—',
    reason: '不适合 K 线',
    checkNote: 'EOD 全付费',
  },

  // ================= 加密货币 =================
  {
    id: 'crypto-binance',
    name: 'Binance',
    market: 'crypto',
    role: '主源',
    score: 96,
    tags: ['已接入', '直连', 'WS实时', '无Key', '1000根'],
    access: ['direct'],
    accessNote: 'CORS *；大陆用户直连可用，但官方对受限地区不提供服务',
    history: '单次 1000 根，16 档间隔（1s~1M）',
    realtime: 'WS kline 实时推送',
    limits: '6000 weight/分钟/IP；超限 429 → 封 IP（递增）',
    reason: '本项目已在用的主源',
    checkUrl: 'https://api.binance.com/api/v3/ping',
  },
  {
    id: 'crypto-okx',
    name: 'OKX',
    market: 'crypto',
    role: '主源',
    score: 91,
    tags: ['直连', 'limit=300', 'WS实时', '无Key'],
    access: ['direct', 'vpn'],
    accessNote: 'CORS 回显 origin；大陆不提供服务（需外网）；1H/4H/1D 大写、返回降序需 reverse',
    history: '单次 limit 最大 300（与 HISTORY_LIMIT 对齐）',
    realtime: 'WS 实时',
    limits: '宽松（实测连发 40 次无 429）',
    reason: 'limit=300 与项目 HISTORY_LIMIT 完美对齐 → 强烈推荐第二源',
    checkUrl: 'https://www.okx.com/api/v5/market/ticker?instId=BTC-USDT',
  },
  {
    id: 'crypto-bybit',
    name: 'Bybit',
    market: 'crypto',
    role: '主源',
    score: 85,
    tags: ['直连', '1000根', 'WS实时', '无Key'],
    access: ['direct', 'vpn'],
    accessNote: 'CORS 回显 origin + credentials；大陆不提供服务',
    history: '单次 limit 最大 1000',
    realtime: 'WS 实时',
    limits: '600 请求/5s/IP，超限 403 停 10 分钟',
    reason: '第三源；直连 + 1000 根',
    checkUrl: 'https://api.bybit.com/v5/market/time',
  },
  {
    id: 'crypto-gate',
    name: 'Gate.io',
    market: 'crypto',
    role: '备选',
    score: 76,
    tags: ['直连', '1000根', '无Key'],
    access: ['direct', 'vpn'],
    accessNote: 'CORS *；秒级时间戳 + 字符串数组需 Number() 转换',
    history: '单次最大 1000，间隔含 10s~30d',
    realtime: 'WS 实时',
    limits: '公开限制宽松',
    reason: '候选；注意时间戳单位',
    checkUrl: 'https://api.gateio.ws/api/v4/spot/tickers?currency_pair=BTC_USDT',
  },
  {
    id: 'crypto-htx',
    name: 'HTX（原火币）',
    market: 'crypto',
    role: '备选',
    score: 70,
    tags: ['直连', '2000根深历史', '无Key'],
    access: ['direct', 'vpn'],
    accessNote: '秒级时间戳 + 升序；品牌/合规问题多，多地受限',
    history: '单次 size 最大 2000（所有源最深）',
    realtime: 'WS 实时',
    limits: '—',
    reason: '可作深历史补充；合规谨慎',
    checkUrl: 'https://api.huobi.pro/market/detail/merged?symbol=btcusdt',
  },
  {
    id: 'crypto-bitget',
    name: 'Bitget',
    market: 'crypto',
    role: '备选',
    score: 68,
    tags: ['直连', '1000根', '无Key'],
    access: ['direct', 'vpn'],
    accessNote: 'granularity 拼写是 1min 而非 1m（传 1m 报 400）；返回降序',
    history: '单次最大 1000，另有 /history-candles 深回溯',
    realtime: 'WS 实时',
    limits: '—',
    reason: '候选；注意参数拼写坑',
    checkUrl: 'https://api.bitget.com/api/v2/spot/public/time',
  },
  {
    id: 'crypto-ccxt',
    name: 'ccxt（聚合）',
    market: 'crypto',
    role: '参考',
    score: 62,
    tags: ['100+交易所', 'Node BFF'],
    access: ['server'],
    accessNote: '服务端 Node 库，浏览器不适用；WS 推送收费（CCXT Pro）',
    history: '随交易所',
    realtime: '公共行情无 key',
    limits: 'CCXT Pro 收费',
    reason: '适合后续做「Node 聚合 BFF」',
    checkNote: '服务端库',
  },
  {
    id: 'crypto-kraken',
    name: 'Kraken',
    market: 'crypto',
    role: '参考',
    score: 58,
    tags: ['需代理', '721根', '命名特殊'],
    access: ['proxy', 'vpn'],
    accessNote: '无 CORS 头必须代理；BTC→XBT、USD→ZUSD 命名特殊',
    history: '每次固定返回 721 根',
    realtime: 'WS 实时',
    limits: '—',
    reason: '浏览器直连不行，仅服务端',
    checkUrl: 'https://api.kraken.com/0/public/Time',
  },
  {
    id: 'crypto-coingecko',
    name: 'CoinGecko',
    market: 'crypto',
    role: '参考',
    score: 52,
    tags: ['需Key', '无分钟K线', '无volume'],
    access: ['direct', 'key', 'vpn'],
    accessNote: '2024 后必须注册 key（Demo 100 次/分）；无逐根分钟 K 线、无 volume',
    history: 'OHLC 聚合粒度（≤1天→30分钟档）',
    realtime: '缓存数据',
    limits: '100 次/分、1 万次/月',
    reason: '不适合 K 线对比',
    checkUrl: 'https://api.coingecko.com/api/v3/ping',
  },
  {
    id: 'crypto-coinmarketcap',
    name: 'CoinMarketCap',
    market: 'crypto',
    role: '排除',
    score: 22,
    tags: ['收费化', '无K线'],
    access: [],
    accessNote: '免费档收紧向付费迁移；无交易所 K 线（OHLCV 需付费）',
    history: '—',
    realtime: '—',
    limits: '—',
    reason: '不适合',
    checkNote: '无免费 K 线',
  },
  {
    id: 'crypto-cryptocompare',
    name: 'CryptoCompare',
    market: 'crypto',
    role: '排除',
    score: 20,
    tags: ['需Key'],
    access: [],
    accessNote: '无 key 实测 401「API key required」；免费档近年收紧',
    history: '—',
    realtime: '—',
    limits: '—',
    reason: '不适合',
    checkNote: '需 key（实测 401）',
  },
  {
    id: 'crypto-coincap',
    name: 'CoinCap',
    market: 'crypto',
    role: '排除',
    score: 20,
    tags: ['免费层消失'],
    access: [],
    accessNote: '文档 301 到 pro.coincap.io（登录墙）；api.coincap.io 实测不可达',
    history: '—',
    realtime: '—',
    limits: '—',
    reason: '公共免费层已消失',
    checkNote: '免费层消失，接口不可达',
  },

  // ================= 期货 =================
  {
    id: 'futures-yahoo',
    name: 'Yahoo Finance（CL=F 等）',
    market: 'futures',
    role: '主源',
    score: 86,
    tags: ['26年全历史', '免Key', '需代理'],
    access: ['vpn', 'proxy'],
    accessNote: '无 CORS 需代理；需外网；须显式传 period1/period2 否则被截断到约 268 根',
    history: 'CL=F 自 2000-08 至今 6618 根',
    realtime: '延时 15 分钟',
    limits: '无 SLA，高频 429',
    reason: '海外期货首选',
    checkUrl: 'https://query1.finance.yahoo.com/v8/finance/chart/CL%3DF?range=5d&interval=1d',
  },
  {
    id: 'futures-sina',
    name: '新浪期货（RB0 主力连续）',
    market: 'futures',
    role: '主源',
    score: 84,
    tags: ['主力连续', '2009至今', '5/15/60分钟', '持仓量'],
    access: ['proxy'],
    accessNote: '无 CORS 需代理转发；GB18030 需转码；带 Referer',
    history: 'RB0 自 2009 年至今全量',
    realtime: '盘中实时',
    limits: '隐性限流、封 IP',
    reason: '国内主力连续首选（已含换月）',
    checkUrl: 'https://hq.sinajs.cn/list=RB0',
  },
  {
    id: 'futures-shfe',
    name: 'SHFE/INE 官方 EOD',
    market: 'futures',
    role: '备选',
    score: 72,
    tags: ['官方', 'settle/持仓', 'JSON'],
    access: ['proxy'],
    accessNote: '无 CORS 需代理；日终文件；合约换月需自算主力连续',
    history: '日线每日全合约',
    realtime: '无盘中',
    limits: '—',
    reason: '日线基准（结算价/持仓量）',
    checkUrl: 'https://www.shfe.com.cn/',
  },
  {
    id: 'futures-cffex',
    name: 'CFFEX 官方 CSV',
    market: 'futures',
    role: '备选',
    score: 70,
    tags: ['官方', 'IF/IC/IM/IH', 'GBK'],
    access: ['proxy'],
    accessNote: 'GBK 日成交 CSV，需代理',
    history: '日线全合约',
    realtime: '无盘中',
    limits: '—',
    reason: '股指期货基准',
    checkUrl: 'https://www.cffex.com.cn/',
  },
  {
    id: 'futures-sina-global',
    name: '新浪海外期货 hf_*',
    market: 'futures',
    role: '备选',
    score: 68,
    tags: ['海外日线', '1996起', 'volume=0'],
    access: ['proxy'],
    accessNote: '海外日线 1996 年起全历史，但 volume=0；需代理',
    history: '1996 年起 7690 根',
    realtime: '海外实时（hf_*）',
    limits: '隐性限流',
    reason: '海外日线兜底（无成交量）',
    checkUrl: 'https://hq.sinajs.cn/list=hf_CL',
  },
  {
    id: 'futures-dce',
    name: 'DCE（大连商品交易所）',
    market: 'futures',
    role: '排除',
    score: 30,
    tags: ['WAF 412'],
    access: ['server'],
    accessNote: '实测被 WAF 412 拦截',
    history: '—',
    realtime: '—',
    limits: '—',
    reason: '程序化接入不行',
    checkUrl: 'https://www.dce.com.cn/',
    checkNote: 'WAF 412 拦截',
  },
  {
    id: 'futures-czce',
    name: 'CZCE（郑州商品交易所）',
    market: 'futures',
    role: '排除',
    score: 28,
    tags: ['空返回'],
    access: ['server'],
    accessNote: '实测接口返回空',
    history: '—',
    realtime: '—',
    limits: '—',
    reason: '程序化接入不行',
    checkNote: '接口空返回',
  },
  {
    id: 'futures-cme',
    name: 'CME 官网',
    market: 'futures',
    role: '排除',
    score: 35,
    tags: ['无公开API'],
    access: [],
    accessNote: '在线 10 分钟延时行情免登录，但无公开 JSON API，历史需订阅',
    history: '—',
    realtime: '网页端',
    limits: '—',
    reason: '无程序化接口',
    checkNote: '无公开 API',
  },
  {
    id: 'futures-quandl',
    name: 'Quandl（CHRIS/CME）',
    market: 'futures',
    role: '排除',
    score: 22,
    tags: ['付费'],
    access: [],
    accessNote: 'CME 系列数据集已转付费',
    history: '—',
    realtime: '—',
    limits: '—',
    reason: '排除',
    checkNote: '已付费',
  },
  {
    id: 'futures-stooq',
    name: 'Stooq（期货）',
    market: 'futures',
    role: '排除',
    score: 22,
    tags: ['反爬验证墙'],
    access: ['server'],
    accessNote: 'SHA-256 PoW JS 反爬挑战，直连拿不到 CSV',
    history: '—',
    realtime: '—',
    limits: '—',
    reason: '反爬成本高',
    checkNote: 'PoW 反爬墙',
  },

  // ================= 基金 =================
  {
    id: 'fund-eastmoney-lsjz',
    name: '天天基金 api.fund lsjz（场外净值）',
    market: 'fund',
    role: '主源',
    score: 86,
    tags: ['全量净值', '免Key', '单位/累计'],
    access: ['proxy'],
    accessNote: '无 CORS 需代理；T 日 16~23 点更新；高频偶发断连（≤2 req/s）',
    history: '成立以来全量（分页）',
    realtime: 'T 日晚更新',
    limits: '无官方限制，实测 ≤2 req/s 稳',
    reason: '场外净值主源（无 OHLC，只画净值曲线）',
    checkUrl: 'https://api.fund.eastmoney.com/f10/lsjz?fundCode=000001&pageIndex=1&pageSize=1',
  },
  {
    id: 'fund-eastmoney-etf',
    name: '东财 push2his（场内 ETF）',
    market: 'fund',
    role: '主源',
    score: 83,
    tags: ['直连', '前复权fqt=1', '真实OHLCV', '实时'],
    access: ['direct'],
    accessNote: 'CORS 反射可直连但 502 频发，建议限速 + 带 Referer + 代理兜底',
    history: '上市以来全量（510300 自 2012）',
    realtime: '盘中实时',
    limits: '无官方限制；实测不稳定',
    reason: '场内 ETF 画 K 线首选（fqt=1 前复权防分红跳空）',
    checkUrl:
      'https://push2his.eastmoney.com/api/qt/stock/kline/get?secid=1.510300&fields1=f1,f2,f3,f4,f5,f6&fields2=f51,f52,f53,f54,f55,f56,f57,f58&klt=101&fqt=1&beg=0&end=20500101&lmt=1',
  },
  {
    id: 'fund-eastmoney-js',
    name: '天天基金 pingzhongdata（JS）',
    market: 'fund',
    role: '主源',
    score: 78,
    tags: ['JS注入', '规模/阶段收益', '免Key'],
    access: ['jsonp'],
    accessNote: '<script> 标签注入绕过 CORS；2026 盘中估值接口已失效勿依赖',
    history: '成立以来全量（毫秒时间戳）',
    realtime: 'T 日晚更新',
    limits: '—',
    reason: '场外全字段净值（规模/阶段收益）',
    checkUrl: 'https://fund.eastmoney.com/pingzhongdata/000001.js',
  },
  {
    id: 'fund-yahoo',
    name: 'Yahoo Finance（美国 ETF）',
    market: 'fund',
    role: '主源',
    score: 75,
    tags: ['SPY全历史', '免Key', '需代理'],
    access: ['vpn', 'proxy'],
    accessNote: '无 CORS 需代理；需外网；延时 15 分钟',
    history: 'SPY 全历史',
    realtime: '延时 15 分钟',
    limits: '无 SLA',
    reason: '美国 ETF 最实用',
    checkUrl: 'https://query1.finance.yahoo.com/v8/finance/chart/SPY?range=1d&interval=1d',
  },
  {
    id: 'fund-sec',
    name: 'SEC EDGAR（美国基金持仓）',
    market: 'fund',
    role: '参考',
    score: 66,
    tags: ['直连', '持仓数据', '季度披露'],
    access: ['direct'],
    accessNote: 'ACAO:* 可直连；持仓/份额季度披露（非行情）；SEC 要求带联系方式 User-Agent',
    history: '2001 起',
    realtime: '季度',
    limits: '有速率限制',
    reason: '美国基金/ETF 持仓直连源',
    checkUrl: 'https://www.sec.gov/',
  },
  {
    id: 'fund-sina-etf',
    name: '新浪 quotes.sina.cn（ETF）',
    market: 'fund',
    role: '备选',
    score: 58,
    tags: ['分钟/日', '无Key'],
    access: ['proxy'],
    accessNote: '无 CORS 需代理；日线仅约 1000 根（4 年）',
    history: '日线约 1000 根；分钟线 5/15/30/60/120/240',
    realtime: '盘中实时（需 Referer）',
    limits: '隐性限流',
    reason: '场内 ETF 备援',
    checkUrl: 'https://quotes.sina.cn/cn/api/jsonp_v2.php/x/CN_MarketDataService.getKLineData?symbol=sh510300&scale=240&datalen=1',
  },
  {
    id: 'fund-danjuan',
    name: '蛋卷 / 雪球',
    market: 'fund',
    role: '排除',
    score: 42,
    tags: ['需Cookie'],
    access: [],
    accessNote: '净值接口需登录 cookie',
    history: '—',
    realtime: '—',
    limits: '—',
    reason: '需 cookie，程序化麻烦',
    checkNote: '需 cookie',
  },
  {
    id: 'fund-csindex',
    name: '中证指数官网',
    market: 'fund',
    role: '排除',
    score: 36,
    tags: ['WAF拦截'],
    access: [],
    accessNote: 'API 被 WAF 拦截',
    history: '—',
    realtime: '—',
    limits: '—',
    reason: '仅指数非 ETF，且被拦',
    checkNote: 'WAF 拦截',
  },
  {
    id: 'fund-exchange',
    name: '沪深交易所（ETF）',
    market: 'fund',
    role: '排除',
    score: 34,
    tags: ['接口半失效'],
    access: [],
    accessNote: '行情 API 参数繁琐/半失效',
    history: '—',
    realtime: '—',
    limits: '—',
    reason: '不建议',
    checkNote: '接口半失效',
  },
  {
    id: 'fund-morningstar',
    name: '晨星 Morningstar',
    market: 'fund',
    role: '排除',
    score: 28,
    tags: ['无免费API'],
    access: [],
    accessNote: '评级数据商业授权，无免费 API',
    history: '—',
    realtime: '—',
    limits: '—',
    reason: '无免费入口',
    checkNote: '无免费 API',
  },
];
